### ISSUE TITLE
Extending compound selectors.

### ISSUE THREAD

**Issue by MattBidewell** [HMPO/hmpo-components#117]
Hi there! 👋🏻 

I'm using the repo at GDS and have found when upgrading to `5.0.3` from `4.6.0` and found an compiler issues when using the `sass` npm module version `1.43.3`.

[Breaking changes note from sass](https://sass-lang.com/documentation/breaking-changes/extend-compound)

I've made the change suggested and raised a PR [here](https://github.com/HMPO/hmpo-components/pull/116).

Thanks in advance 😁

**Comment by HughePaul** [comment]
Released as hmpo-components@5.1.0
