### ISSUE TITLE
Using hmpo-radios the govuk-frontend radio button divider does not get translated

### ISSUE THREAD

**Issue by gds-jbentham** [HMPO/hmpo-components#136]
When using the hmpo-radios component.
If you add a divider to your radio button in the fields.js like the below
```

    newRadioButtons: {
      type: "radios",
      label: "",
      legend: "",
      items: [{value:"Option One"}, {value:"Option Two"}, {divider: "or"}, {value:"Option Three"}],
      validate: ["required"],
    },
```
https://design-system.service.gov.uk/components/radios/
<img width="851" alt="Screenshot 2023-02-01 at 17 23 06" src="https://user-images.githubusercontent.com/105647376/216117188-ab64ee68-e5f8-4cbd-bc6b-270ca9dcd6cd.png">

When you add locales the divider text does not get translated like the other items.
If you add this line             
`if (item.divider) item.divider = translate(contentKey + '.items.' + item.divider + '.label');` 
Into globals.js hmpoGetItems. Then you can use the same syntax in your locales files to translate the divider text
_fields.yml_
```
newRadioButtons:
  items:
    or:
      label: <or in desired language>
```

**Comment by HughePaul** [comment]
I'd rather leave the legacy/govuk behaviour where the divider being a string is what gets rendered. instead i propose having:`
{ divider: true }` to use a default localisation key lookup of `fields.newRadioButtons.divider.label` and `fields.default.divider.label` or specifying a key: `{ divider: true, key: 'full.localisation.key' }` to match key specifying functionality of items.

https://github.com/HMPO/hmpo-components/pull/139/files

Also the divider items should be ignored in hmpo-form-wizard when auto-adding an items validator:

https://github.com/HMPO/hmpo-form-wizard/pull/189/files

**Comment by HughePaul** [comment]
merged and released (including hmpo-form-wizard update to ignore divider items)
